name: NocturneItems
version: '1.0-SNAPSHOT'
main: me.giveblock.nocturneItems.NocturneItems
api-version: '1.21'

commands:
  nocturnegive:
    description: default give command
    aliases:
      - 'nocgive'
      - 'ngive'

permissions:
  nocturneitems.give:
    description: 'Give Item permission'
    default: false